review_logical_access:
    description: Compare system access levels against authorized access matrix
    agent: logical_access_reviewer
    dependencies: [] 
    priority: 1
    inputs:
      - data/access_report.csv
      - data/access_matrix.csv
    outputs:
      - output/access_findings.md
    expected_output: A markdown file containing access-related findings with title, background, discrepancies, and user feedback section

review_transaction_limits:
    description: Analyze transaction approvals against authorized limits
    agent: limit_reviewer
    dependencies: []
    priority: 1
    inputs:
      - data/limit_authorization.pdf
      - data/transaction_logs.csv
    outputs:
      - output/limit_findings.md
    expected_output: A markdown file containing limit-related findings with title, background, discrepancies, and user feedback section

review_transactions:
    description: Analyze transactions for policy violations
    agent: transaction_reviewer
    dependencies: []
    priority: 1
    inputs:
      - data/transaction_policy.pdf
      - data/transaction_records.csv
    outputs:
      - output/transaction_findings.md
    expected_output: A markdown file containing transaction-related findings with title, background, discrepancies, and user feedback section

review_audit_trail:
    description: Compare system changes against change tickets
    agent: audit_trail_reviewer
    dependencies: []
    priority: 1
    inputs:
      - data/audit_trail.csv
      - data/change_tickets.csv
    outputs:
      - output/audit_trail_findings.md
    expected_output: A markdown file containing audit trail-related findings with title, background, discrepancies, and user feedback section

compile_audit_report:
    description: Compile all findings into comprehensive audit report
    agent: audit_report_writer
    dependencies: 
      - review_logical_access
      - review_transaction_limits
      - review_transactions
      - review_audit_trail
    priority: 2
    inputs:
      - output/access_findings.md
      - output/limit_findings.md
      - output/transaction_findings.md
      - output/audit_trail_findings.md
    outputs:
      - output/final_audit_report.md
    expected_output: A comprehensive audit report with executive summaries, detailed findings, risk ratings, and management actions